/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'breads' : null } |
  { 'cakes' : null } |
  { 'pastries' : null } |
  { 'drinks' : null };
export interface CustomerRewards {
  'freeTreats' : bigint,
  'principal' : Principal,
  'itemsPurchased' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : Category,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface RewardsConfig { 'itemsPerFreeTreat' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoteChoice = { 'shadow' : null } |
  { 'silver' : null };
export interface VoteResults {
  'totalVotes' : bigint,
  'shadowVotes' : bigint,
  'silverVotes' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], bigint>,
  'adjustCustomerRewards' : ActorMethod<[Principal, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'castVote' : ActorMethod<[VoteChoice], undefined>,
  'claimFreeTreat' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerRewards' : ActorMethod<[], CustomerRewards>,
  'getCustomerRewardsByPrincipal' : ActorMethod<[Principal], CustomerRewards>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[Category], Array<MenuItem>>,
  'getRewardsConfig' : ActorMethod<[], RewardsConfig>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoteResults' : ActorMethod<[], VoteResults>,
  'hasVoted' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordPurchase' : ActorMethod<[Principal, bigint], undefined>,
  'registerAdmin' : ActorMethod<[string], undefined>,
  'removeMenuItem' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
  'updateRewardsConfig' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];