/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'breads' : IDL.Null,
  'cakes' : IDL.Null,
  'pastries' : IDL.Null,
  'drinks' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : Category,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VoteChoice = IDL.Variant({
  'shadow' : IDL.Null,
  'silver' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CustomerRewards = IDL.Record({
  'freeTreats' : IDL.Nat,
  'principal' : IDL.Principal,
  'itemsPurchased' : IDL.Nat,
});
export const RewardsConfig = IDL.Record({ 'itemsPerFreeTreat' : IDL.Nat });
export const VoteResults = IDL.Record({
  'totalVotes' : IDL.Nat,
  'shadowVotes' : IDL.Nat,
  'silverVotes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
  'adjustCustomerRewards' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'castVote' : IDL.Func([VoteChoice], [], []),
  'claimFreeTreat' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerRewards' : IDL.Func([], [CustomerRewards], ['query']),
  'getCustomerRewardsByPrincipal' : IDL.Func(
      [IDL.Principal],
      [CustomerRewards],
      ['query'],
    ),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRewardsConfig' : IDL.Func([], [RewardsConfig], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoteResults' : IDL.Func([], [VoteResults], ['query']),
  'hasVoted' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPurchase' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'registerAdmin' : IDL.Func([IDL.Text], [], []),
  'removeMenuItem' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
  'updateRewardsConfig' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'breads' : IDL.Null,
    'cakes' : IDL.Null,
    'pastries' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : Category,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VoteChoice = IDL.Variant({ 'shadow' : IDL.Null, 'silver' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CustomerRewards = IDL.Record({
    'freeTreats' : IDL.Nat,
    'principal' : IDL.Principal,
    'itemsPurchased' : IDL.Nat,
  });
  const RewardsConfig = IDL.Record({ 'itemsPerFreeTreat' : IDL.Nat });
  const VoteResults = IDL.Record({
    'totalVotes' : IDL.Nat,
    'shadowVotes' : IDL.Nat,
    'silverVotes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
    'adjustCustomerRewards' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'castVote' : IDL.Func([VoteChoice], [], []),
    'claimFreeTreat' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerRewards' : IDL.Func([], [CustomerRewards], ['query']),
    'getCustomerRewardsByPrincipal' : IDL.Func(
        [IDL.Principal],
        [CustomerRewards],
        ['query'],
      ),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRewardsConfig' : IDL.Func([], [RewardsConfig], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoteResults' : IDL.Func([], [VoteResults], ['query']),
    'hasVoted' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPurchase' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'registerAdmin' : IDL.Func([IDL.Text], [], []),
    'removeMenuItem' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
    'updateRewardsConfig' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };